include: package:flutter_lints/flutter.yaml

linter:

  rules:
    avoid_print: false  
    prefer_single_quotes: true 
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    avoid_empty_else: true
    avoid_types_as_parameter_names: true
    hash_and_equals: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    no_duplicate_case_values: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    avoid_shadowing_type_parameters: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    file_names: true
    non_constant_identifier_names: true
    null_check_on_nullable_type_parameter: true
    package_prefixed_library_names: true
    prefer_generic_function_type_aliases: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    unnecessary_overrides: true
    void_checks: true
    depend_on_referenced_packages: true