name: hire_me
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  http: ^0.13.4
  flutter_svg: ^1.1.1+1
  intl: ^0.17.0
  carousel_slider: ^4.1.1
  url_launcher: ^6.1.5
  flutter_local_notifications: ^9.7.0
  flutter_native_splash: ^2.2.4
  connectivity_plus: ^2.3.5
  package_info_plus: ^1.4.2
  device_info_plus: ^4.0.0
  infinite_scroll_pagination: ^3.2.0
  equatable: ^2.0.3
  shimmer: ^2.0.0
  badges: ^2.0.3
  flutter_inappwebview: ^5.4.3+7
  animations: ^2.0.3
  app_settings: ^4.1.8
  introduction_screen: ^3.0.1
  fluro: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/data/

  fonts:
    - family: HireRegular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

    - family: HireBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: HireItalic
      fonts:
        - asset: assets/fonts/OpenSans-Italic.ttf

    - family: HireLight
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
